### ISSUE TITLE
Add new Features in Menu bar

### ISSUE THREAD

**Issue by bindu-07** [bindu-07/CrowdChatting#1]
In this App already "Sign Out" feature exists in Menu bar.
--------------------------   || -----------------------------
So, your task is that Add another two features Called "My Profile" and  "Settings" in menu bar.

**Comment by codeDamon** [comment]
Want just menu options or both pages(My Profile and Settings)?

**Comment by bindu-07** [comment]
menu option is already created and "sign Out" item is already here. your tusk is add two more item "My Profile" and "Settings".
hope you are understand.

**Comment by codeDamon** [comment]
Ya I understood.
Please, assign this issue to me.

**Comment by codeDamon** [comment]
What functionality you need me to add when user selects these(My profile and Settings) menus?

**Comment by codeDamon** [comment]
Preview of menu in the app now: 

![screenshot_preview](https://user-images.githubusercontent.com/59572531/106256333-25b5cd80-6241-11eb-8171-53446ada9b2e.jpg)

**Comment by bindu-07** [comment]
Yes and 
Atleast Toast message appear when click.

**Comment by codeDamon** [comment]
> Yes and
> Atleast Toast message appear when click.

Okay, creating PR.

**Comment by codeDamon** [comment]
I think issue needs to be closed.
