### ISSUE TITLE
Create Settings page 

### ISSUE THREAD

**Issue by bindu-07** [bindu-07/CrowdChatting#3]
### Create a Settings XML file and Complete the following following task..

- [1] **user's Notifications** using Checkbox [Enable/Disable]
- [2] **dark** **Mode** [Enable/Disable]
--------------------------------- || ------------------------------------
demo of my another Project for some idea ..
![Screenshot (21)](https://user-images.githubusercontent.com/72141546/104819626-bad5c100-5854-11eb-98f1-d3a0bc964f1a.png)

**Comment by codeDamon** [comment]
For this issue, Do we need to add dark mode and notification functionalities or just have to create settings page with these options?

**Comment by bindu-07** [comment]
yes, you need to add dark mode and notification functionalities.

**Comment by bindu-07** [comment]
it is good issue to solve. best of luck

**Comment by codeDamon** [comment]
> yes, you need to add dark mode and notification functionalities.

There is other issue related to notifications #7 . Why implementing notifications in this issue?

**Comment by bindu-07** [comment]
notification handling on #7 issue. you can implement just notification check box and dark mode functionalities.
hope you understood.
