### ISSUE TITLE
Message Loading Animation

### ISSUE THREAD

**Issue by bindu-07** [bindu-07/CrowdChatting#6]
If you see the Progressbar is not visible just after user's sign In.

So, your task is that fix the issue for better user Experience.

**Comment by codeDamon** [comment]
Did you want some loading animation? 
If that's so, assign this issue to me.

**Comment by bindu-07** [comment]
Yes issue about progress bar.

**Comment by codeDamon** [comment]
We have to add a ProgressBar after user sign-in. That's it?

**Comment by bindu-07** [comment]
progress bar is already added but not working so fix the issue

**Comment by codeDamon** [comment]
Okay :+1:

**Comment by codeDamon** [comment]
I think issue needs to be closed.
